### ISSUE TITLE
atom 1.17+: Renames tab to the left of the one it should rename

### ISSUE THREAD

**Issue by sfredo** [erikjansson/atom-tab-title#2]
Apparently atom 1.17 has a tab-title for the file tree section and this module is now renaming the tab to the left of the one it should rename, probably because it's not considering this new permanent first tab.

**Comment by Jesperbk** [comment]
I have created a pull request that resolves this issue.

**Comment by sfredo** [comment]
Thanks, will it break the renaming on previous versions of atom?

**Comment by Jesperbk** [comment]
I ran a quick test in v1.16, and it seems to remain compatible with that version.

**Comment by koenlek** [comment]
@sfredo : could you consider merging it? This bug makes the plugin unusable for me currently.

**Comment by erikjansson** [comment]
Merged the PR. Thanks for the fix, @Jesperbk!
